apiVersion: v1
kind: Service
metadata:
  name: tracelabel-couchdb
  labels:
    app: tracelabel
    org: tracelabel
    node: peer
    tier: db
spec:
  ports:
    - port: 5984
  selector:
    app: tracelabel
    org: tracelabel
    node: peer
    tier: db
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracelabel-db-pv-claim
  labels:
    app: tracelabel
    org: brand1
    node: peer
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: couchdb
  labels:
    app: tracelabel
    org: tracelabel
    node: peer
    tier: db
spec:
  selector:
    matchLabels:
      app: tracelabel
      org: tracelabel
      node: peer
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracelabel
        org: tracelabel
        node: peer
        tier: db
    spec:
      containers:
      - image: registry.au-syd.bluemix.net/tlabel/fabric-couchdb:latest
        name: couchdb
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: tracelabel-peer-db
              key: user
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tracelabel-peer-db
              key: password
        ports:
        - containerPort: 5984
          name: couchdb
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/local/var/lib/couchdb
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: tracelabel-db-pv-claim