apiVersion: v1
kind: Service
metadata:
  name: tracelabel-peer
  labels:
    app: tracelabel
    org: tracelabel
    node: peer
    tier: middle
spec:
  type: NodePort
  ports:
    - port: 7051
      name: listen
      nodePort: 30051
    - port: 7053
      name: events
      nodePort: 30053
  selector:
    app: tracelabel
    org: tracelabel
    node: peer
    tier: middle


---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: peer
  labels:
    app: tracelabel
    org: tracelabel
    node: peer
    tier: middle
spec:
  selector:
    matchLabels:
      app: tracelabel
      org: tracelabel
      node: peer
      tier: middle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracelabel
        org: tracelabel
        node: peer
        tier: middle
    spec:
      containers:
      - image: registry.au-syd.bluemix.net/tracelabel/fabric-peer:latest
        name: fabric-peer
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_ID
          value: peer0.tracelabel.com
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: debug
        - name: CORE_PEER_LOCALMSPID
          value: TraceLabelMSP
        - name: oER_GENERAL_LOCALMSPID
          value: TraceLabelMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/msp/peer/
        - name: CORE_PEER_ADDRESS
          value: peer0.tracelabel.com:7051
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: tracelabel-couchdb:5984
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          valueFrom:
                secretKeyRef:
                  name: tracelabel-peer-db
                  key: user
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: tracelabel-peer-db
                  key: password
        ports:
        - containerPort: 7051
          name: listen
        - containerPort: 7053
          name: evnets
        volumeMounts:
        - name: msp
          mountPath: /etc/hyperledger/msp/peer
          readOnly: true
        - name: users
          mountPath: /etc/hyperledger/msp/users
          readOnly: true
        - name: dockersocket
          mountPath: /host/var/run/docker.sock
      volumes:
      - name: msp
        secret:
          secretName: tracelabel-peer-msp
          items:
          - key: peer0.tracelabel.com-cert.pem
            path: signcerts/peer0.tracelabel.com-cert.pem
          - key: 7dc60b88d647a14d02ad312154a4710a7823d52d6c7e429ecd801ec59e54a3a3_sk
            path: keystore/7dc60b88d647a14d02ad312154a4710a7823d52d6c7e429ecd801ec59e54a3a3_sk
          - key: ca.tracelabel.com-cert.pem
            path: cacerts/ca.tracelabel.com-cert.pem
          - key: tlsca.tracelabel.com-cert.pem
            path: tlscacerts/tlsca.tracelabel.com-cert.pem
          - key: admin_cert
            path: admincerts/Admin@tracelabel.com-cert.pem
      - name: users
        secret:
          secretName: tracelabel-peer-users
          items:
          - key: ca_cert
            path: msp/cacerts/ca.tracelabel.com-cert.pem
          - key: admin_cert
            path: msp/admincerts/Admin@tracelabel.com-cert.pem
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
