
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: couchdb
  labels:
    app: fabcar
    org: brand1
    node: peer
    tier: db
spec:
  selector:
    matchLabels:
      app: fabcar
      org: brand1
      node: peer
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fabcar
        org: brand1
        node: peer
        tier: db
    spec:
      containers:
      - image: registry.au-syd.bluemix.net/tlabel/fabric-couchdb:latest
        name: couchdb
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: brand1-peer-db
              key: user
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: brand1-peer-db
              key: password
        ports:
        - containerPort: 5984
          name: couchdb
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/local/var/lib/couchdb
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: brand1-peer-pv-claim