apiVersion: v1
kind: Service
metadata:
  name: tracelabel-ca
  labels:
    app: tracelabel
    org: tracelabel
    node: ca
    tier: middle
spec:
  type: NodePort
  ports:
    - port: 7054
      nodePort: 30054
  selector:
    app: tracelabel
    org: tracelabel
    node: ca
    tier: middle

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracelabel-ca-pv-claim
  labels:
    app: tracelabel
    org: tracelabel
    node: ca
    tier: middle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracelabel-ca-pv-claim2
  labels:
    app: tracelabel
    org: tracelabel
    node: ca
    tier: middle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ca
  labels:
    app: tracelabel
    org: tracelabel
    node: ca
    tier: middle
spec:
  selector:
    matchLabels:
      app: tracelabel
      org: tracelabel
      node: ca
      tier: middle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracelabel
        org: tracelabel
        node: ca
        tier: middle
    spec:
      containers:
      - image: registry.eu-de.bluemix.net/hyperledger/fabric-ca:latest
        name: fabric-ca
        command: ["sh"]
        args: ["-c", "fabric-ca-server start -b admin:adminpw -d --cafiles ../ca1/cfg/fabric-ca-config.yaml --cafiles ../ca2/cfg/fabric-ca-config.yaml"]
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server/ca
        ports:
        - containerPort: 7054
          name: ca
        volumeMounts:
        - name: ca
          mountPath: /etc/hyperledger/fabric-ca-server/ca
        - name: ca1
          mountPath: /etc/hyperledger/fabric-ca-server/ca1/cfg
          readOnly: true
        - name: ca-data
          mountPath: /etc/hyperledger/fabric-ca-server/ca1/data
          subPath: ca1/msp
        - name: ca2
          mountPath: /etc/hyperledger/fabric-ca-server/ca2/cfg
          readOnly: false
        - name: ca-data
          mountPath: /etc/hyperledger/fabric-ca-server/ca2/data
          subPath: ca2/msp
      volumes:
      - name: ca
        secret:
          secretName: tracelabel-default-ca
      - name: ca1
        secret:
          secretName: tracelabel-ca1
      - name: ca2
        secret:
          secretName: tracelabel-ca2
      - name: ca-data
        persistentVolumeClaim:
          claimName: tracelabel-ca-pv-claim
