apiVersion: v1
kind: PersistentVolume
metadata:
  name: tracelabel-ca-pv-0
  labels:
    type: local
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/pv-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tracelabel-ca-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/pv-0

