# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: TLabel
    Domain: tracelabel.com
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: TLabel
    Domain: tracelabel.com
    CA:
      Hostname: ca # implicitly org1.example.com
      Country: RU
      Province: Moscow
      Locality: Moscow
      #OrganizationalUnit: Head
      #StreetAddress: address for org # default nil
      #PostalCode: postalCode for org # default nil
    Specs:
       - Hostname: orderer # peer used for validation  
       - Hostname: peer-1 # peer used for validation
       - Hostname: peer-2 # peer used for validation
       - Hostname: gw-peer-1 # gateway peer for distributors not having own peers
       - Hostname: gw-peer-2 # gateway peer for distributors not having own peers
    Template:
      Count: 2
    Users:
      Count: 2


  - Name: Band1
    Domain: brand1.com
    CA:
      Hostname: ca
    Template:
      Count: 2
    Users:
      Count: 1
  
  
  # ---------------------------------------------------------------------------
  # Org2
  # ---------------------------------------------------------------------------
  - Name: Brand2
    Domain: brand2.com
    CA:
       Hostname: ca.brand2.com
    Template:
      Count: 2
    Users:
      Count: 1
  

  - Name: Distributor-1
    Domain: distributor-1.com
    Template:
      Count: 2
    Users:
      Count: 1         


  - Name: Distributor-2
    Domain: distributor-2.com
    Template:
      Count: 2
    Users:
      Count: 1    

     